name: strengthwise
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  flutter_native_splash: ^2.3.1
  get_it: ^7.6.0
  shared_preferences: ^2.1.2
  image_picker: ^0.8.7+5
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.7.10
  fl_chart: ^1.1.1
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  devtools_mcp_extension: ^0.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
