name: strengthwise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  cloud_firestore: ^5.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
